# Generated by Django 4.1.2 on 2022-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_cateogry_transaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piggybank",
            name="current_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="piggybank",
            name="total_amout",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="usersavings",
            name="amount",
            field=models.FloatField(),
        ),
    ]
