# Generated by Django 3.2 on 2022-10-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_piggybank_current_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggybank',
            name='name',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
